export type Category =
  | "Machine Learning"
  | "Web Development"
  | "Cooking"
  | "Gaming"
  | "Fitness"
  | "Music"
  | "Travel"
  | "Science"
  | "Shorts";

export interface Video {
  id: string;
  title: string;
  description: string;
  category: Category;
  tags: string[];
  thumbnail: string;
  duration: string;
  views: string;
  likes: number;
  channel: string;
  channelAvatar: string;
  uploadedAt: string;
  subscribers: string;
}

export const VIDEOS: Video[] = [
  // ── MACHINE LEARNING ──────────────────────────────────────────────
  {
    id: "ml-001",
    title: "Neural Networks Explained from Scratch",
    description:
      "A deep dive into how neural networks work, covering perceptrons, activation functions, backpropagation, and gradient descent with visual examples.",
    category: "Machine Learning",
    tags: ["neural network", "deep learning", "backpropagation", "AI", "machine learning", "gradient descent", "perceptron", "weights", "layers"],
    thumbnail: "https://images.unsplash.com/photo-1717501219263-9aa2d6a768d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "24:17",
    views: "2.1M",
    likes: 89000,
    channel: "AI Academy",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=AI&backgroundColor=4f46e5",
    uploadedAt: "3 weeks ago",
    subscribers: "1.2M",
  },
  {
    id: "ml-002",
    title: "Convolutional Neural Networks for Image Classification",
    description:
      "Learn how CNNs work for image recognition tasks. We cover convolutional layers, pooling, feature maps, and build a classifier from scratch in Python.",
    category: "Machine Learning",
    tags: ["CNN", "image classification", "convolutional", "neural network", "deep learning", "computer vision", "feature maps", "pooling", "AI"],
    thumbnail: "https://images.unsplash.com/photo-1678845530864-18a666ca9762?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "31:44",
    views: "1.4M",
    likes: 62000,
    channel: "AI Academy",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=AI&backgroundColor=4f46e5",
    uploadedAt: "1 month ago",
    subscribers: "1.2M",
  },
  {
    id: "ml-003",
    title: "Transformer Architecture: Attention is All You Need",
    description:
      "Understand the transformer model that powers GPT and BERT. We cover self-attention, multi-head attention, positional encoding, and encoder-decoder structure.",
    category: "Machine Learning",
    tags: ["transformer", "attention mechanism", "GPT", "BERT", "NLP", "deep learning", "self-attention", "machine learning", "AI", "neural network"],
    thumbnail: "https://images.unsplash.com/photo-1717501219263-9aa2d6a768d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-30",
    duration: "42:08",
    views: "3.5M",
    likes: 145000,
    channel: "DeepMind Hub",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=DM&backgroundColor=7c3aed",
    uploadedAt: "2 months ago",
    subscribers: "890K",
  },
  {
    id: "ml-004",
    title: "Reinforcement Learning: Teaching Agents to Play Games",
    description:
      "An introduction to reinforcement learning — Q-learning, policy gradients, and training an agent to master Atari games using deep RL techniques.",
    category: "Machine Learning",
    tags: ["reinforcement learning", "Q-learning", "policy gradient", "agent", "reward", "deep learning", "AI", "machine learning", "game AI"],
    thumbnail: "https://images.unsplash.com/photo-1678845530864-18a666ca9762?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&hue-rotate=60",
    duration: "38:22",
    views: "1.8M",
    likes: 74000,
    channel: "DeepMind Hub",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=DM&backgroundColor=7c3aed",
    uploadedAt: "5 weeks ago",
    subscribers: "890K",
  },
  {
    id: "ml-005",
    title: "Random Forests & Gradient Boosting: Ensemble Methods",
    description:
      "Master ensemble learning with Random Forests and XGBoost. Covers bagging, boosting, feature importance, and hyperparameter tuning.",
    category: "Machine Learning",
    tags: ["random forest", "gradient boosting", "XGBoost", "ensemble", "machine learning", "bagging", "decision tree", "AI", "sklearn"],
    thumbnail: "https://images.unsplash.com/photo-1717501219263-9aa2d6a768d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=-10",
    duration: "27:55",
    views: "956K",
    likes: 41000,
    channel: "ML Masters",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=MM&backgroundColor=059669",
    uploadedAt: "2 months ago",
    subscribers: "456K",
  },

  // ── WEB DEVELOPMENT ───────────────────────────────────────────────
  {
    id: "wd-001",
    title: "React 18: Concurrent Rendering & Suspense Deep Dive",
    description:
      "Explore React 18's concurrent features including useTransition, useDeferredValue, and Suspense for data fetching. Build snappy, modern UIs.",
    category: "Web Development",
    tags: ["React", "concurrent rendering", "Suspense", "hooks", "JavaScript", "frontend", "web development", "UI", "useTransition"],
    thumbnail: "https://images.unsplash.com/photo-1591267990532-e5bdb1b0ceb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "33:10",
    views: "1.2M",
    likes: 58000,
    channel: "Code Craft",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CC&backgroundColor=0ea5e9",
    uploadedAt: "3 weeks ago",
    subscribers: "780K",
  },
  {
    id: "wd-002",
    title: "Build a REST API with Node.js & Express",
    description:
      "Create a production-ready REST API using Node.js, Express, JWT authentication, MongoDB, and deploy it to the cloud.",
    category: "Web Development",
    tags: ["Node.js", "Express", "REST API", "JavaScript", "backend", "web development", "MongoDB", "JWT", "authentication"],
    thumbnail: "https://images.unsplash.com/photo-1583508915901-b5f84c1dcde1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "51:22",
    views: "2.3M",
    likes: 97000,
    channel: "Code Craft",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CC&backgroundColor=0ea5e9",
    uploadedAt: "1 month ago",
    subscribers: "780K",
  },
  {
    id: "wd-003",
    title: "CSS Grid & Flexbox Mastery: Modern Layouts",
    description:
      "Master modern CSS layout techniques with Grid and Flexbox. Build complex responsive layouts with clean, readable code.",
    category: "Web Development",
    tags: ["CSS", "Grid", "Flexbox", "layout", "responsive", "web development", "frontend", "HTML", "design"],
    thumbnail: "https://images.unsplash.com/photo-1660616246653-e2c57d1077b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "44:05",
    views: "890K",
    likes: 44000,
    channel: "DevStyle",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=DS&backgroundColor=f59e0b",
    uploadedAt: "6 weeks ago",
    subscribers: "320K",
  },
  {
    id: "wd-004",
    title: "TypeScript for React Developers",
    description:
      "Level up your React apps with TypeScript — generics, interfaces, union types, type guards, and advanced patterns for large codebases.",
    category: "Web Development",
    tags: ["TypeScript", "React", "JavaScript", "web development", "frontend", "types", "generics", "interfaces", "coding"],
    thumbnail: "https://images.unsplash.com/photo-1583508915901-b5f84c1dcde1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-20",
    duration: "39:48",
    views: "1.6M",
    likes: 71000,
    channel: "DevStyle",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=DS&backgroundColor=f59e0b",
    uploadedAt: "2 months ago",
    subscribers: "320K",
  },
  {
    id: "wd-005",
    title: "Next.js 14: App Router & Server Components",
    description:
      "Build full-stack apps with Next.js 14 App Router, Server Components, Server Actions, and streaming for maximum performance.",
    category: "Web Development",
    tags: ["Next.js", "React", "server components", "web development", "frontend", "full-stack", "JavaScript", "routing", "performance"],
    thumbnail: "https://images.unsplash.com/photo-1591267990532-e5bdb1b0ceb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-10",
    duration: "58:14",
    views: "3.1M",
    likes: 128000,
    channel: "Code Craft",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CC&backgroundColor=0ea5e9",
    uploadedAt: "1 week ago",
    subscribers: "780K",
  },

  // ── COOKING ───────────────────────────────────────────────────────
  {
    id: "ck-001",
    title: "Authentic Italian Pasta from Scratch",
    description:
      "Learn to make fresh pasta dough, various shapes, and classic sauces like cacio e pepe, carbonara, and amatriciana — the traditional Italian way.",
    category: "Cooking",
    tags: ["pasta", "Italian cuisine", "cooking", "recipe", "dough", "sauce", "carbonara", "food", "chef"],
    thumbnail: "https://images.unsplash.com/photo-1746494557939-2d305c1c834a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "28:33",
    views: "4.2M",
    likes: 192000,
    channel: "Chef Marco",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CM&backgroundColor=ef4444",
    uploadedAt: "2 weeks ago",
    subscribers: "2.1M",
  },
  {
    id: "ck-002",
    title: "Meal Prep Sunday: 5 Days of Healthy Meals",
    description:
      "Prep a full week of nutritious meals in under 2 hours. High-protein, balanced macros, and delicious flavors for busy weekdays.",
    category: "Cooking",
    tags: ["meal prep", "healthy eating", "cooking", "nutrition", "food", "recipe", "protein", "diet", "weekly meals"],
    thumbnail: "https://images.unsplash.com/photo-1606859191214-25806e8e2423?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "35:41",
    views: "2.8M",
    likes: 117000,
    channel: "Healthy Bites",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=HB&backgroundColor=22c55e",
    uploadedAt: "4 weeks ago",
    subscribers: "1.5M",
  },
  {
    id: "ck-003",
    title: "The Perfect Sourdough Bread: Complete Guide",
    description:
      "Master sourdough bread baking — starter creation, fermentation, shaping, scoring, and baking in a Dutch oven for a perfect crust.",
    category: "Cooking",
    tags: ["sourdough", "bread baking", "cooking", "fermentation", "recipe", "dough", "food", "baking", "yeast"],
    thumbnail: "https://images.unsplash.com/photo-1746494557939-2d305c1c834a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-15",
    duration: "47:18",
    views: "6.3M",
    likes: 274000,
    channel: "Chef Marco",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=CM&backgroundColor=ef4444",
    uploadedAt: "3 months ago",
    subscribers: "2.1M",
  },
  {
    id: "ck-004",
    title: "Thai Street Food: Pad Thai & Green Curry",
    description:
      "Authentic Thai cooking at home. Learn the secrets to wok hei, making curry pastes from scratch, and balancing sweet, sour, and spicy flavors.",
    category: "Cooking",
    tags: ["Thai food", "pad thai", "curry", "cooking", "recipe", "Asian cuisine", "food", "wok", "spicy"],
    thumbnail: "https://images.unsplash.com/photo-1606859191214-25806e8e2423?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&hue-rotate=30",
    duration: "26:09",
    views: "1.9M",
    likes: 83000,
    channel: "World Kitchen",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=WK&backgroundColor=f97316",
    uploadedAt: "5 weeks ago",
    subscribers: "678K",
  },
  {
    id: "ck-005",
    title: "Chocolate Desserts: Lava Cake to Mousse",
    description:
      "Indulgent chocolate dessert recipes from molten lava cakes to airy chocolate mousse and silky ganache tarts. Perfect for any occasion.",
    category: "Cooking",
    tags: ["chocolate", "dessert", "baking", "cooking", "recipe", "food", "cake", "mousse", "sweet"],
    thumbnail: "https://images.unsplash.com/photo-1746494557939-2d305c1c834a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=10",
    duration: "22:44",
    views: "3.7M",
    likes: 161000,
    channel: "Healthy Bites",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=HB&backgroundColor=22c55e",
    uploadedAt: "1 month ago",
    subscribers: "1.5M",
  },

  // ── GAMING ────────────────────────────────────────────────────────
  {
    id: "gm-001",
    title: "Elden Ring: Complete Beginner's Build Guide",
    description:
      "A comprehensive guide for new Elden Ring players — best starting builds, essential tips, boss strategies, and the fastest route through the Lands Between.",
    category: "Gaming",
    tags: ["Elden Ring", "RPG", "gaming", "build guide", "boss strategy", "soulslike", "fantasy", "gameplay", "tips"],
    thumbnail: "https://images.unsplash.com/photo-1643489069237-3548135218c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "44:29",
    views: "7.2M",
    likes: 312000,
    channel: "GG Masters",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=GG&backgroundColor=8b5cf6",
    uploadedAt: "2 weeks ago",
    subscribers: "3.4M",
  },
  {
    id: "gm-002",
    title: "Valorant: Pro Aim Training Routine",
    description:
      "Train like a Valorant pro — crosshair placement, flicking, tracking drills, deathmatch routines, and mental game strategies for ranking up.",
    category: "Gaming",
    tags: ["Valorant", "FPS", "gaming", "aim training", "esports", "shooter", "competitive", "ranked", "tips"],
    thumbnail: "https://images.unsplash.com/photo-1772587003187-65b32c91df91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "19:52",
    views: "5.4M",
    likes: 228000,
    channel: "ProPlay",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PP&backgroundColor=dc2626",
    uploadedAt: "3 weeks ago",
    subscribers: "2.8M",
  },
  {
    id: "gm-003",
    title: "Minecraft Survival Ultra Hardcore — Episode 1",
    description:
      "Starting a new ultra hardcore Minecraft survival world with custom rules. No respawning, limited resources, and unforgiven difficulty settings.",
    category: "Gaming",
    tags: ["Minecraft", "survival", "gaming", "hardcore", "sandbox", "crafting", "building", "let's play", "adventure"],
    thumbnail: "https://images.unsplash.com/photo-1643489069237-3548135218c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-20",
    duration: "37:14",
    views: "2.1M",
    likes: 95000,
    channel: "GG Masters",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=GG&backgroundColor=8b5cf6",
    uploadedAt: "1 week ago",
    subscribers: "3.4M",
  },
  {
    id: "gm-004",
    title: "The Future of PC Gaming in 2025",
    description:
      "Exploring upcoming GPU releases, ray tracing advancements, AI-powered frame generation, cloud gaming vs local hardware, and what to build for.",
    category: "Gaming",
    tags: ["PC gaming", "GPU", "hardware", "gaming", "technology", "ray tracing", "cloud gaming", "esports", "build"],
    thumbnail: "https://images.unsplash.com/photo-1772587003187-65b32c91df91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-10",
    duration: "29:03",
    views: "1.3M",
    likes: 57000,
    channel: "TechGamer",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TG&backgroundColor=14b8a6",
    uploadedAt: "4 weeks ago",
    subscribers: "567K",
  },
  {
    id: "gm-005",
    title: "Spider-Man 2: Full Story Walkthrough No Commentary",
    description:
      "Complete cinematic walkthrough of Marvel's Spider-Man 2 — full story, all cutscenes, and key gameplay moments in stunning 4K quality.",
    category: "Gaming",
    tags: ["Spider-Man", "action adventure", "gaming", "walkthrough", "story", "PlayStation", "superhero", "gameplay", "cutscenes"],
    thumbnail: "https://images.unsplash.com/photo-1643489069237-3548135218c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=-5",
    duration: "1:42:17",
    views: "8.9M",
    likes: 398000,
    channel: "ProPlay",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=PP&backgroundColor=dc2626",
    uploadedAt: "2 months ago",
    subscribers: "2.8M",
  },

  // ── FITNESS ───────────────────────────────────────────────────────
  {
    id: "ft-001",
    title: "30-Minute Full Body HIIT Workout — No Equipment",
    description:
      "Burn calories and build strength with this intense 30-minute HIIT session. Zero equipment needed — perfect for home workouts and beginners.",
    category: "Fitness",
    tags: ["HIIT", "workout", "fitness", "no equipment", "exercise", "cardio", "strength training", "home workout", "burn calories"],
    thumbnail: "https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "31:05",
    views: "12.4M",
    likes: 543000,
    channel: "FitForce",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=FF&backgroundColor=f97316",
    uploadedAt: "1 month ago",
    subscribers: "5.6M",
  },
  {
    id: "ft-002",
    title: "Morning Yoga Flow for Flexibility & Calm",
    description:
      "A gentle 20-minute morning yoga flow to improve flexibility, posture, and mental clarity. Suitable for all levels from beginners to intermediate.",
    category: "Fitness",
    tags: ["yoga", "morning routine", "fitness", "flexibility", "meditation", "mindfulness", "stretching", "wellness", "calm"],
    thumbnail: "https://images.unsplash.com/photo-1592895792095-85fa785192a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "22:18",
    views: "8.7M",
    likes: 376000,
    channel: "ZenFit",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=ZF&backgroundColor=a3e635",
    uploadedAt: "2 weeks ago",
    subscribers: "3.2M",
  },
  {
    id: "ft-003",
    title: "Powerlifting for Beginners: Squat, Bench, Deadlift",
    description:
      "Master the three big lifts with proper form, programming principles, and progressive overload strategies for strength building.",
    category: "Fitness",
    tags: ["powerlifting", "strength training", "squat", "bench press", "deadlift", "fitness", "gym", "workout", "muscle"],
    thumbnail: "https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-20",
    duration: "40:57",
    views: "3.1M",
    likes: 134000,
    channel: "FitForce",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=FF&backgroundColor=f97316",
    uploadedAt: "6 weeks ago",
    subscribers: "5.6M",
  },
  {
    id: "ft-004",
    title: "Running for Fat Loss: Science-Based Protocol",
    description:
      "Evidence-based running strategies for fat loss — zone 2 cardio, interval training, weekly volume, nutrition timing, and recovery.",
    category: "Fitness",
    tags: ["running", "fat loss", "cardio", "fitness", "exercise", "weight loss", "LISS", "intervals", "endurance"],
    thumbnail: "https://images.unsplash.com/photo-1592895792095-85fa785192a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-10",
    duration: "27:36",
    views: "5.4M",
    likes: 231000,
    channel: "ZenFit",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=ZF&backgroundColor=a3e635",
    uploadedAt: "3 weeks ago",
    subscribers: "3.2M",
  },
  {
    id: "ft-005",
    title: "Calisthenics Mastery: From Pull-ups to Muscle-up",
    description:
      "Progressive calisthenics training from zero pull-ups to your first muscle-up. Step-by-step progressions, mobility work, and programming.",
    category: "Fitness",
    tags: ["calisthenics", "pull-ups", "muscle-up", "bodyweight", "fitness", "strength training", "workout", "gym", "exercise"],
    thumbnail: "https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=-5",
    duration: "35:49",
    views: "4.2M",
    likes: 182000,
    channel: "FitForce",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=FF&backgroundColor=f97316",
    uploadedAt: "1 month ago",
    subscribers: "5.6M",
  },

  // ── MUSIC ─────────────────────────────────────────────────────────
  {
    id: "mu-001",
    title: "Learn Guitar in 30 Days: Beginner to Intermediate",
    description:
      "Complete guitar course covering chords, scales, strumming patterns, fingerpicking, music theory, and your first songs in 30 days.",
    category: "Music",
    tags: ["guitar", "music", "learn guitar", "chords", "beginner", "music theory", "strumming", "acoustic", "instrument"],
    thumbnail: "https://images.unsplash.com/photo-1752830457847-97ac95b93a07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "48:22",
    views: "9.1M",
    likes: 403000,
    channel: "Music Lab",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=ML&backgroundColor=ec4899",
    uploadedAt: "3 months ago",
    subscribers: "4.5M",
  },
  {
    id: "mu-002",
    title: "Music Production: Make Beats in FL Studio 21",
    description:
      "Create professional beats from scratch in FL Studio — drums, basslines, melody, mixing, mastering, and exporting your tracks.",
    category: "Music",
    tags: ["music production", "FL Studio", "beat making", "mixing", "mastering", "music", "producer", "hip-hop", "electronic"],
    thumbnail: "https://images.unsplash.com/photo-1710282965041-8296adaf2403?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "56:44",
    views: "2.4M",
    likes: 104000,
    channel: "BeatLab",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=BL&backgroundColor=6366f1",
    uploadedAt: "5 weeks ago",
    subscribers: "890K",
  },
  {
    id: "mu-003",
    title: "Piano for Beginners: Read Sheet Music in 1 Hour",
    description:
      "Learn to read sheet music and play your first piano pieces in just one hour. Covers notes, rhythm, time signatures, and hand coordination.",
    category: "Music",
    tags: ["piano", "sheet music", "music", "beginner", "instrument", "music theory", "keyboard", "classical", "notes"],
    thumbnail: "https://images.unsplash.com/photo-1710282965041-8296adaf2403?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-20",
    duration: "62:08",
    views: "15.3M",
    likes: 672000,
    channel: "Music Lab",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=ML&backgroundColor=ec4899",
    uploadedAt: "4 months ago",
    subscribers: "4.5M",
  },
  {
    id: "mu-004",
    title: "Music Theory Crash Course: Scales & Harmony",
    description:
      "Understand scales, intervals, chords, harmony, and how they all connect. Essential music theory for guitarists, pianists, and producers.",
    category: "Music",
    tags: ["music theory", "scales", "harmony", "chords", "intervals", "music", "composition", "guitar", "piano"],
    thumbnail: "https://images.unsplash.com/photo-1752830457847-97ac95b93a07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-15",
    duration: "37:55",
    views: "6.8M",
    likes: 295000,
    channel: "BeatLab",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=BL&backgroundColor=6366f1",
    uploadedAt: "2 months ago",
    subscribers: "890K",
  },
  {
    id: "mu-005",
    title: "Singing Lessons: Chest Voice, Mix & Head Voice",
    description:
      "Develop your vocal range with exercises for chest voice, mixed voice, and head voice. Includes warm-ups, breathing techniques, and resonance tips.",
    category: "Music",
    tags: ["singing", "vocal training", "music", "voice", "chest voice", "head voice", "breathing", "lessons", "performance"],
    thumbnail: "https://images.unsplash.com/photo-1752830457847-97ac95b93a07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=5",
    duration: "41:19",
    views: "3.9M",
    likes: 168000,
    channel: "Music Lab",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=ML&backgroundColor=ec4899",
    uploadedAt: "6 weeks ago",
    subscribers: "4.5M",
  },

  // ── TRAVEL ────────────────────────────────────────────────────────
  {
    id: "tv-001",
    title: "Japan on a Budget: 2 Weeks for $1500",
    description:
      "Complete budget travel guide to Japan — cheap accommodation, food on the go, hidden gems, transportation hacks, and must-see experiences.",
    category: "Travel",
    tags: ["Japan", "budget travel", "travel", "Asia", "tourism", "backpacking", "culture", "food", "adventure"],
    thumbnail: "https://images.unsplash.com/photo-1673505413397-0cd0dc4f5854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "29:14",
    views: "8.3M",
    likes: 361000,
    channel: "Wanderlust",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=WL&backgroundColor=0891b2",
    uploadedAt: "1 month ago",
    subscribers: "4.1M",
  },
  {
    id: "tv-002",
    title: "Bali Hidden Gems: Beyond the Tourist Traps",
    description:
      "Discover Bali's secret beaches, hidden temples, local warungs, and offbeat adventures that most tourists never find on this tropical island.",
    category: "Travel",
    tags: ["Bali", "Indonesia", "travel", "beach", "tropical", "island", "adventure", "hidden gems", "tourism"],
    thumbnail: "https://images.unsplash.com/photo-1631535152690-ba1a85229136?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "24:38",
    views: "5.7M",
    likes: 248000,
    channel: "TravelVibes",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TV&backgroundColor=16a34a",
    uploadedAt: "3 weeks ago",
    subscribers: "2.7M",
  },
  {
    id: "tv-003",
    title: "Solo Trekking the Himalayas: Annapurna Circuit",
    description:
      "A raw, honest account of solo trekking the Annapurna Circuit in Nepal — gear, permits, altitude sickness, tea houses, and life-changing views.",
    category: "Travel",
    tags: ["trekking", "Himalayas", "Nepal", "hiking", "travel", "adventure", "mountains", "solo travel", "backpacking"],
    thumbnail: "https://images.unsplash.com/photo-1673505413397-0cd0dc4f5854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-10",
    duration: "52:07",
    views: "4.1M",
    likes: 178000,
    channel: "Wanderlust",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=WL&backgroundColor=0891b2",
    uploadedAt: "2 months ago",
    subscribers: "4.1M",
  },
  {
    id: "tv-004",
    title: "Road Trip USA: Route 66 End to End",
    description:
      "Driving the legendary Route 66 from Chicago to Santa Monica. Diners, desert landscapes, quirky roadside attractions, and the spirit of America.",
    category: "Travel",
    tags: ["Route 66", "road trip", "USA", "travel", "adventure", "driving", "American West", "tourism", "road"],
    thumbnail: "https://images.unsplash.com/photo-1631535152690-ba1a85229136?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-5",
    duration: "43:22",
    views: "6.8M",
    likes: 294000,
    channel: "TravelVibes",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=TV&backgroundColor=16a34a",
    uploadedAt: "5 weeks ago",
    subscribers: "2.7M",
  },
  {
    id: "tv-005",
    title: "Living Nomadically: Work from Anywhere in the World",
    description:
      "How to become a digital nomad — finding remote work, best visa options, co-working spaces, internet setup, and managing life across time zones.",
    category: "Travel",
    tags: ["digital nomad", "remote work", "travel", "lifestyle", "work from anywhere", "adventure", "freedom", "visa", "backpacking"],
    thumbnail: "https://images.unsplash.com/photo-1673505413397-0cd0dc4f5854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=-5",
    duration: "38:51",
    views: "11.2M",
    likes: 487000,
    channel: "Wanderlust",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=WL&backgroundColor=0891b2",
    uploadedAt: "1 week ago",
    subscribers: "4.1M",
  },

  // ── SCIENCE ───────────────────────────────────────────────────────
  {
    id: "sc-001",
    title: "Quantum Computing: From Qubits to Quantum Advantage",
    description:
      "A clear explanation of quantum computing concepts — qubits, superposition, entanglement, quantum gates, and what quantum advantage really means.",
    category: "Science",
    tags: ["quantum computing", "qubits", "physics", "science", "quantum mechanics", "technology", "superposition", "entanglement", "research"],
    thumbnail: "https://images.unsplash.com/photo-1774277602359-d5dfed73aa98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800",
    duration: "34:29",
    views: "3.8M",
    likes: 163000,
    channel: "ScienceNow",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=SN&backgroundColor=6366f1",
    uploadedAt: "4 weeks ago",
    subscribers: "2.3M",
  },
  {
    id: "sc-002",
    title: "CRISPR Gene Editing: Rewriting Life's Code",
    description:
      "How CRISPR-Cas9 works, its applications in medicine, agriculture, and biotechnology, plus the ethical debates surrounding gene editing.",
    category: "Science",
    tags: ["CRISPR", "gene editing", "biology", "science", "genetics", "DNA", "research", "biotechnology", "medicine"],
    thumbnail: "https://images.unsplash.com/photo-1774277602359-d5dfed73aa98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-20",
    duration: "28:16",
    views: "5.2M",
    likes: 226000,
    channel: "BioSpark",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=BS&backgroundColor=10b981",
    uploadedAt: "6 weeks ago",
    subscribers: "1.8M",
  },
  {
    id: "sc-003",
    title: "Black Holes: Everything We Know (2025 Update)",
    description:
      "Updated with latest discoveries — event horizons, Hawking radiation, black hole imaging, and what happens when you fall into one.",
    category: "Science",
    tags: ["black holes", "astrophysics", "space", "science", "physics", "cosmology", "event horizon", "gravity", "universe"],
    thumbnail: "https://images.unsplash.com/photo-1774277602359-d5dfed73aa98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&bri=-10",
    duration: "41:53",
    views: "18.7M",
    likes: 821000,
    channel: "ScienceNow",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=SN&backgroundColor=6366f1",
    uploadedAt: "3 months ago",
    subscribers: "2.3M",
  },
  {
    id: "sc-004",
    title: "The Human Brain: Neural Plasticity & Learning",
    description:
      "How the brain rewires itself through learning and experience — neuroplasticity, long-term potentiation, memory consolidation, and practical applications.",
    category: "Science",
    tags: ["neuroscience", "brain", "neuroplasticity", "science", "learning", "biology", "memory", "psychology", "research"],
    thumbnail: "https://images.unsplash.com/photo-1774277602359-d5dfed73aa98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&hue-rotate=30",
    duration: "36:44",
    views: "7.4M",
    likes: 321000,
    channel: "BioSpark",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=BS&backgroundColor=10b981",
    uploadedAt: "2 weeks ago",
    subscribers: "1.8M",
  },
  {
    id: "sc-005",
    title: "Climate Science Explained: Data, Models & Solutions",
    description:
      "A data-driven look at climate science — CO2 trajectories, climate models, tipping points, renewable energy solutions, and what individuals can do.",
    category: "Science",
    tags: ["climate science", "environment", "science", "data", "renewable energy", "CO2", "research", "earth", "sustainability"],
    thumbnail: "https://images.unsplash.com/photo-1774277602359-d5dfed73aa98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800&auto=format&sat=-5",
    duration: "49:11",
    views: "9.1M",
    likes: 394000,
    channel: "ScienceNow",
    channelAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=SN&backgroundColor=6366f1",
    uploadedAt: "1 month ago",
    subscribers: "2.3M",
  },
];

export const CATEGORIES: Category[] = [
  "Machine Learning",
  "Web Development",
  "Cooking",
  "Gaming",
  "Fitness",
  "Music",
  "Travel",
  "Science",
  "Shorts",
];
